In [9]:
import numpy as np
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.linspace(0,10,5) #linearly spaced 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.eye(5) #identity matrix of order 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
2*np.eye(3)

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [13]:
np.random.rand(5) #random numbers lying between zero and one

array([0.30964997, 0.71152122, 0.89981987, 0.02570322, 0.79805486])

In [14]:
np.random.rand(3,2)

array([[0.8816758 , 0.76742452],
       [0.44863053, 0.88570367],
       [0.23347433, 0.04894594]])

In [16]:
np.random.randn(3,3) #mat(3x3), random no not limited to range 0 to 1

array([[ 0.29022586, -0.52004182,  0.10149838],
       [ 0.13833012, -0.16475913, -0.10694284],
       [ 0.34383991,  1.06554141,  1.00210437]])

In [17]:
np.random.randint(1,100) #gives a random number in given range

5

In [19]:
np.random.randint(1,100,5) #gives array of random numbers in given range

array([25, 69,  7, 90, 46])

In [21]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [23]:
arr = np.arange(0,50,5)

In [26]:
arr = arr.reshape(2,5)

In [28]:
arr

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [30]:
arr.max()

45

In [38]:
arr.argmin() #index of min value in the array

0

In [39]:
arr.argmax() #index of max value in the array

9

In [41]:
arr = np.arange(10)

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr.shape #shape gives the dimension of the array or the matrix

(10,)

In [44]:
arr.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
import numpy as np
arr = np.random.randint(0,8,9)
arr.reshape(3,3)

In [ ]:
for i in ran